main:
    resource: "@MainBundle/Resources/config/routing/test.xml"
    prefix:   /


fc_user:
    resource: "@UserBundle/Resources/config/routing/user.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"